language: go
sudo: false
go:
  - 1.6.3
  - 1.7.1
  - tip
install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
script:
  - go vet ./...
  - golint -set_exit_status ./...
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -race -v ./...
